/*
username: ema
password: 11ema
*/



CREATE TABLE UtentiRegistrati (
    utente_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(256) UNIQUE,
    cognome             VARCHAR(256),
    email               VARCHAR(256),
    password            VARCHAR(256) NOT NULL,
    urlFotoProfilo      VARCHAR(256)
);






--Popolamento tabella utenti
INSERT INTO UtentiRegistrati (utente_id, name,cognome, email, password, urlfotoprofilo)
VALUES (
default,
        'Luca',
        'Manca',
        'luca@gmail.con',
        '1',
        '.jpg');

INSERT INTO UtentiRegistrati (utente_id, name,cognome, email, password, urlfotoprofilo)
VALUES (default,
        'Emanuel',
        'Fois',
        'ema@gmail.con',
        '1',
        '.jpg');

INSERT INTO UtentiRegistrati (utente_id, name,cognome, email, password, urlfotoprofilo)
VALUES (default,
        'Bobo',
        'Puddu',
        'bobo@gmail.con',
        '1',
        '.jpg');

INSERT INTO UtentiRegistrati (utente_id, name,cognome, email, password, urlfotoprofilo)
VALUES (default,
        'Bizio',
        'Basciu',
        'bizio@gmail.con',
        '1',
        '.jpg');




