
/*
username: ema
password: ema
*/

CREATE TABLE UtentiRegistrati(
    utente_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                VARCHAR(256) UNIQUE,
    cognome             VARCHAR(256),
    email               VARCHAR(256) UNIQUE,
    password            VARCHAR(30),
    urlFotoProfilo      VARCHAR(256)
);

CREATE TABLE postType (
    posttype_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    posttype_name VARCHAR(32)
);

CREATE TABLE posts (
    post_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(1024),
    type INTEGER,
    FOREIGN KEY (type) REFERENCES postType(postType_id),
    author INTEGER,
    FOREIGN KEY (author) REFERENCES UtentiRegistrati(utente_id)
);

--Popolamento tabella Post
INSERT INTO posts (post_id, content, type, author)
VALUES (default,
        'Ciao, miei schiavi. Datemi cibo! Adesso! Miaomiaomiaomiaomiao!',
        1,
        1);

INSERT INTO posts (post_id, content, type, author)
VALUES (default,
        'img/djanni1.jpg',
        2,
        1);
--Popolamento tabella PostType
INSERT INTO posttype (posttype_id, posttype_name)
VALUES (default, 'TEXT');

INSERT INTO posttype (posttype_id, posttype_name)
VALUES (default, 'IMAGE');



--Popolamento tabella utenti
INSERT INTO UtentiRegistrati (utente_id, nome,cognome, email, password, urlfotoprofilo)
VALUES (
        default,
        'Luca',
        'Manca',
        'luca@gmail.con',
        '1',
        '.jpg');

INSERT INTO UtentiRegistrati (utente_id, nome,cognome, email, password, urlfotoprofilo)
VALUES (default,
        'Emanuel',
        'Fois',
        'ema@gmail.con',
        '1',
        '.jpg');

INSERT INTO UtentiRegistrati (utente_id, nome,cognome, email, password, urlfotoprofilo)
VALUES (default,
        'Bobo',
        'Puddu',
        'bobo@gmail.con',
        '1',
        '.jpg');

INSERT INTO UtentiRegistrati (utente_id, nome,cognome, email, password, urlfotoprofilo)
VALUES (default,
        'Bizio',
        'Basciu',
        'bizio@gmail.con',
        '1',
        '.jpg');




